// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// LinkRepository is an autogenerated mock type for the LinkRepository type
type LinkRepository struct {
	mock.Mock
}

// SaveLink provides a mock function with given fields: ctx, key, url, expiration
func (_m *LinkRepository) SaveLink(ctx context.Context, key string, url string, expiration time.Duration) (bool, error) {
	ret := _m.Called(ctx, key, url, expiration)

	if len(ret) == 0 {
		panic("no return value specified for SaveLink")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Duration) (bool, error)); ok {
		return rf(ctx, key, url, expiration)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Duration) bool); ok {
		r0 = rf(ctx, key, url, expiration)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, time.Duration) error); ok {
		r1 = rf(ctx, key, url, expiration)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLink provides a mock function with given fields: ctx, key
func (_m *LinkRepository) GetLink(ctx context.Context, key string) (string, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for GetLink")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewLinkRepository creates a new instance of LinkRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLinkRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *LinkRepository {
	mock := &LinkRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
