// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/nguyenthienan91/bookmark-manager/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// HealthCheck is an autogenerated mock type for the HealthCheck type
type HealthCheck struct {
	mock.Mock
}

// Check provides a mock function with given fields: ctx
func (_m *HealthCheck) Check(ctx context.Context) (model.HealthCheckResponse, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Check")
	}

	var r0 model.HealthCheckResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (model.HealthCheckResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) model.HealthCheckResponse); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(model.HealthCheckResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewHealthCheck creates a new instance of HealthCheck. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHealthCheck(t interface {
	mock.TestingT
	Cleanup(func())
}) *HealthCheck {
	mock := &HealthCheck{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
