// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ShortenLink is an autogenerated mock type for the ShortenLink type
type ShortenLink struct {
	mock.Mock
}

// Shorten provides a mock function with given fields: ctx, url, expSeconds
func (_m *ShortenLink) Shorten(ctx context.Context, url string, expSeconds int) (string, error) {
	ret := _m.Called(ctx, url, expSeconds)

	if len(ret) == 0 {
		panic("no return value specified for Shorten")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) (string, error)); ok {
		return rf(ctx, url, expSeconds)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int) string); ok {
		r0 = rf(ctx, url, expSeconds)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(ctx, url, expSeconds)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewShortenLink creates a new instance of ShortenLink. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewShortenLink(t interface {
	mock.TestingT
	Cleanup(func())
}) *ShortenLink {
	mock := &ShortenLink{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
